// Generated by Open Ontology from support-desk@0.1.0. Regenerate instead of editing.
// Best-effort @osdk/maker source for Palantir Foundry Ontology as Code; see docs/foundry.md.
//
// Not compiled as modeled:
// - open-work: Datalog queries have no Ontology as Code equivalent; it was left out
// - escalations: Datalog queries have no Ontology as Code equivalent; it was left out
// - tickets-by-status: Datalog queries have no Ontology as Code equivalent; it was left out

import { defineAction, defineLink, defineObject } from "@osdk/maker";

export const Customer = defineObject({
  apiName: "Customer",
  displayName: "Customer",
  pluralDisplayName: "Customers",
  description: "An organisation that raises tickets.",
  primaryKeyPropertyApiName: "id",
  titlePropertyApiName: "name",
  properties: { id: { type: "string", displayName: "ID" }, name: { type: "string", displayName: "Name" } },
});

export const Engineer = defineObject({
  apiName: "Engineer",
  displayName: "Engineer",
  pluralDisplayName: "Engineers",
  primaryKeyPropertyApiName: "id",
  titlePropertyApiName: "name",
  properties: { id: { type: "string", displayName: "ID" }, name: { type: "string", displayName: "Name" } },
});

export const Ticket = defineObject({
  apiName: "Ticket",
  displayName: "Ticket",
  pluralDisplayName: "Tickets",
  primaryKeyPropertyApiName: "id",
  titlePropertyApiName: "title",
  properties: {
    id: { type: "string", displayName: "ID" },
    title: { type: "string", displayName: "Title" },
    customerId: { type: "string", displayName: "Customer ID" },
    status: { type: "string", displayName: "Status" },
    priority: { type: "double", displayName: "Priority" },
    openedAt: { type: "timestamp", displayName: "Opened At" },
  },
});

export const EscalatedToLink = defineObject({
  apiName: "EscalatedToLink",
  displayName: "Escalated To Link",
  pluralDisplayName: "Escalated To Links",
  primaryKeyPropertyApiName: "id",
  titlePropertyApiName: "reason",
  properties: {
    id: { type: "string", displayName: "ID" },
    fromId: { type: "string", displayName: "Ticket ID" },
    toId: { type: "string", displayName: "Engineer ID" },
    reason: { type: "string", displayName: "Reason" },
    at: { type: "timestamp", displayName: "At" },
  },
});

export const ticketCustomerLink = defineLink({
  apiName: "ticket-customer",
  one: {
    object: Customer,
    metadata: { apiName: "tickets", displayName: "Ticket", pluralDisplayName: "Tickets" },
  },
  toMany: {
    object: Ticket,
    metadata: { apiName: "customer", displayName: "Customer", pluralDisplayName: "Customers" },
  },
  manyForeignKeyProperty: "customerId",
});

export const escalatedToFromLink = defineLink({
  apiName: "escalated-to-from",
  one: {
    object: Ticket,
    metadata: {
      apiName: "escalatedToLinks",
      displayName: "Escalated To Link",
      pluralDisplayName: "Escalated To Links",
    },
  },
  toMany: {
    object: EscalatedToLink,
    metadata: { apiName: "from", displayName: "Ticket", pluralDisplayName: "Tickets" },
  },
  manyForeignKeyProperty: "fromId",
});

export const escalatedToToLink = defineLink({
  apiName: "escalated-to-to",
  one: {
    object: Engineer,
    metadata: {
      apiName: "escalatedToIncomingLinks",
      displayName: "Escalated To Link",
      pluralDisplayName: "Escalated To Links",
    },
  },
  toMany: {
    object: EscalatedToLink,
    metadata: { apiName: "to", displayName: "Engineer", pluralDisplayName: "Engineers" },
  },
  manyForeignKeyProperty: "toId",
});

export const escalatedToLink = defineLink({
  apiName: "escalated-to",
  many: {
    object: Ticket,
    metadata: { apiName: "escalatedTo", displayName: "Engineer", pluralDisplayName: "Engineers" },
    linkToIntermediary: escalatedToFromLink,
  },
  toMany: {
    object: Engineer,
    metadata: { apiName: "escalatedToTickets", displayName: "Ticket", pluralDisplayName: "Tickets" },
    linkToIntermediary: escalatedToToLink,
  },
  intermediaryObjectType: EscalatedToLink,
});

export const openTicketAction = defineAction({
  apiName: "open-ticket",
  displayName: "Open Ticket",
  status: "active",
  parameters: [
    {
      id: "ticket",
      displayName: "Ticket",
      type: "string",
      validation: { required: true, allowedValues: { type: "text" } },
    },
    {
      id: "customer",
      displayName: "Customer",
      type: { type: "objectReference", objectReference: { objectTypeId: Customer.apiName } },
      validation: { required: true, allowedValues: { type: "objectQuery" } },
    },
    {
      id: "title",
      displayName: "Title",
      type: "string",
      validation: { required: true, allowedValues: { type: "text" } },
    },
    {
      id: "priority",
      displayName: "Priority",
      type: "double",
      validation: { required: true, allowedValues: { type: "range" } },
    },
  ],
  rules: [
    {
      type: "addObjectRule",
      addObjectRule: {
        objectTypeId: Ticket.apiName,
        propertyValues: {
          id: { type: "parameterId", parameterId: "ticket" },
          title: { type: "parameterId", parameterId: "title" },
          customerId: {
            type: "objectParameterPropertyValue",
            objectParameterPropertyValue: { parameterId: "customer", propertyTypeId: "id" },
          },
          status: { type: "staticValue", staticValue: { type: "string", string: "open" } },
          priority: { type: "parameterId", parameterId: "priority" },
          openedAt: { type: "currentTime", currentTime: {} },
        },
        structFieldValues: {},
      },
    },
  ],
  entities: {
    affectedInterfaceTypes: [],
    affectedObjectTypes: [Ticket.apiName],
    affectedLinkTypes: [],
    typeGroups: [],
  },
});

export const escalateTicketAction = defineAction({
  apiName: "escalate-ticket",
  displayName: "Escalate Ticket",
  status: "active",
  parameters: [
    {
      id: "ticket",
      displayName: "Ticket",
      type: { type: "objectReference", objectReference: { objectTypeId: Ticket.apiName } },
      validation: { required: true, allowedValues: { type: "objectQuery" } },
    },
    {
      id: "engineer",
      displayName: "Engineer",
      type: { type: "objectReference", objectReference: { objectTypeId: Engineer.apiName } },
      validation: { required: true, allowedValues: { type: "objectQuery" } },
    },
    {
      id: "reason",
      displayName: "Reason",
      type: "string",
      validation: { required: true, allowedValues: { type: "text" } },
    },
  ],
  rules: [
    {
      type: "modifyObjectRule",
      modifyObjectRule: {
        objectToModify: "ticket",
        propertyValues: {
          status: { type: "staticValue", staticValue: { type: "string", string: "escalated" } },
        },
        structFieldValues: {},
      },
    },
    {
      type: "addObjectRule",
      addObjectRule: {
        objectTypeId: EscalatedToLink.apiName,
        propertyValues: {
          id: { type: "uniqueIdentifier", uniqueIdentifier: {} },
          fromId: {
            type: "objectParameterPropertyValue",
            objectParameterPropertyValue: { parameterId: "ticket", propertyTypeId: "id" },
          },
          toId: {
            type: "objectParameterPropertyValue",
            objectParameterPropertyValue: { parameterId: "engineer", propertyTypeId: "id" },
          },
          reason: { type: "parameterId", parameterId: "reason" },
          at: { type: "currentTime", currentTime: {} },
        },
        structFieldValues: {},
      },
    },
  ],
  entities: {
    affectedInterfaceTypes: [],
    affectedObjectTypes: [Ticket.apiName, EscalatedToLink.apiName],
    affectedLinkTypes: [],
    typeGroups: [],
  },
});

export const closeTicketAction = defineAction({
  apiName: "close-ticket",
  displayName: "Close Ticket",
  status: "active",
  parameters: [
    {
      id: "ticket",
      displayName: "Ticket",
      type: { type: "objectReference", objectReference: { objectTypeId: Ticket.apiName } },
      validation: { required: true, allowedValues: { type: "objectQuery" } },
    },
  ],
  rules: [
    {
      type: "modifyObjectRule",
      modifyObjectRule: {
        objectToModify: "ticket",
        propertyValues: { status: { type: "staticValue", staticValue: { type: "string", string: "closed" } } },
        structFieldValues: {},
      },
    },
  ],
  entities: {
    affectedInterfaceTypes: [],
    affectedObjectTypes: [Ticket.apiName],
    affectedLinkTypes: [],
    typeGroups: [],
  },
});
